apiVersion: apps/v1
kind: Deployment
metadata:
  name: nockolds-db
  labels:
    username: "nockolds"
    env: "test"
    app: nockolds-db
spec:
  replicas: 1
  selector:
    matchLabels:
      username: "nockolds"
      env: "test"
      app: nockolds-db
  template:
    metadata:
      labels:
        username: "nockolds"
        env: "test"
        app: nockolds-db
    spec:
      containers:
        - name: deployment
          image: redis:5.0.0
          volumeMounts:
          - name: nockolds-db-data
            mountPath: "/data"
      volumes:
      - name: nockolds-db-data
        persistentVolumeClaim:
          claimName: nockolds-db-data
