apiVersion: v1
kind: Service
metadata:
  name: nockolds-db
spec:
  type: ClusterIP
  selector:
    username: "nockolds"
    env: "test"
    app: nockolds-db
  ports:
  - name: nockolds-db
    port: 6379
    targetPort: 6379
