apiVersion: apps/v1
kind: Deployment
metadata:
  name: nockolds-worker
  labels:
    username: nockolds
    app: nockolds-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nockolds-worker
  template:
    metadata:
      labels:
        username: nockolds
        app: nockolds-worker
    spec:
      containers:
        - name: worker
          imagePullPolicy: Always
          image: colenockolds/nockolds-app:1.0
          command: ["python", "worker.py"]
          env:
            - name: WORKER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: REDIS_IP
              value: "10.99.153.76"
