apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nockolds-db-data
  labels:
    username: "nockolds"
    env: "test"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
