version: '3'
services:
     web:
        build: ./web
        container_name: nockolds_redis
        ports:
           - 5023:5000
        volumes:
           - ./data/animals.json:/animals.json
     redis:
        image: redis:latest
        ports:
            - 6403:6379
        volumes:
            - ./config/redis.conf:/redis.conf
            - ./mydata/:/data
        command: [ "redis-server", "/redis.conf" ]
