apiVersion: apps/v1
kind: Deployment
metadata:
  name: nockolds-worker-hw7
  labels:
    username: nockolds
    app: nockolds-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nockolds-worker
  template:
    metadata:
      labels:
        username: nockolds
        app: nockolds-worker
    spec:
      containers:
        - name: worker
          imagePullPolicy: Always
          image: colenockolds/nockoldshw7:1.0
          command: ["python", "worker.py"]
          #command: ["sleep", "99999999"]
          env:
            - name: WORKER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: REDIS_IP
              value: "10.104.203.97"
