apiVersion: v1
kind: Service
metadata:
  name: nockolds-test-service-redis
spec:
  type: ClusterIP
  selector:
    username: "nockolds"
    env: "test"
    app: nockolds-test-redis
  ports:
  - name: nockolds-test-service-redis
    port: 6379
    targetPort: 6379
