NSPACE="nockolds"
APP="nockolds-app"
VER="0.3.0"
RPORT="6403"
FPORT="5023"
UID="827385"
GID="815499"

build:
    docker build -t ${NSPACE}/${APP}-db:${VER} \
                 -f docker/Dockerfile.db \
                 ./


